### ISSUE TITLE
[Feature] 减少实际体积，将指导视频替换为实时绘制

### ISSUE THREAD

**Issue by DXElecWork** [Ksuserkqy/SportScoreSystem#1]
指导视频相对来说占用空间过分巨大，影响项目clone等操作。且对于小型服务器部署不利，可转为canvas直接绘制动态示意图 / 互动遮罩指引来解决。

**Comment by DXElecWork** [comment]
PS: 直接贴教程视频是很早古的做法了，考虑到用户群体使用习惯应当换成mask + 引导提示了。

**Comment by Ksuserkqy** [comment]
收到，将在 `v1.2.5` 版本改进视频问题

**Comment by DXElecWork** [comment]
Temporary stale.
